version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # root-level requirements.txt
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "pip"
    directory: "/agents/local_agent1"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "build(deps)"

  - package-ecosystem: "pip"
    directory: "/agents/local_agent2"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - dependencies
      - python
    commit-message:
      prefix: "build(deps)"
